name: "Refactor Request"
description: Request to change code to make it easier to maintain, avoid bugs and technical debt.
title: "[REFACTOR] <title>"
labels: ["refactor"]
body:
  - type: markdown
    attributes:
      value: |
        - If you have questions about the project or need help, you can ask in our [Discord chat][https://discord.gg/TrgqXnY2Vf].
        - Please do your best to search for duplicate requests before filing a new requests.
        - Fill out the information below to the best of your ability. Thank you!
  - type: dropdown
    attributes:
      label: Target platform
      description: Which platform should this feature be added to?
      options:
        - Launcher
        - Online Version
        - Server
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the request
      description: |
        Provide a clear and concise description of what needs refactoring.
        - Propose solutions if possible
        - If there is any existing issue related to this, please link it here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: If you have any additional information for us, please add them here.
    validations:
      required: false