name: Launcher

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  npm-linux:
    runs-on: ubuntu-22.04
    container: fedora:38
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: >
          dnf install -y
          git
          wine mono-devel mono-winfx
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - working-directory: launcher
        run: npm install
      - working-directory: launcher
        run: npm run make
      - uses: actions/upload-artifact@v4
        with:
          name: quadradius-launcher-linux-x64-zip
          path: launcher/out/make/zip/linux/x64/*.zip
          if-no-files-found: error
          compression-level: 0

  npm-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - working-directory: launcher
        run: npm install
      - working-directory: launcher
        run: npm run make
      - uses: actions/upload-artifact@v4
        with:
          name: quadradius-launcher-win32-x64-zip
          path: launcher/out/make/zip/win32/x64/*.zip
          if-no-files-found: error
          compression-level: 0
      - uses: actions/upload-artifact@v4
        with:
          name: quadradius-launcher-win32-x64-setup
          path: launcher/out/make/squirrel.windows/x64/*.exe
          if-no-files-found: error
          compression-level: 0
      - uses: actions/upload-artifact@v4
        with:
          name: quadradius-launcher-win32-x64-nupkg
          path: launcher/out/make/squirrel.windows/x64/*.nupkg
          if-no-files-found: error
          compression-level: 0

  flatpak:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: quadradius-launcher-flatpak.flatpak
          manifest-path: launcher/com.github.Fruktus.QuadradiusLauncher.yml
          cache-key: flatpak-builder-${{ github.sha }}
