name: Server

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'
      - name: Install
        working-directory: server
        run: pip install '.[dev]'
      - name: Run flake8
        working-directory: server
        run: flake8

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9.18', '3.10.13', '3.11.8', '3.12.2' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        working-directory: server
        run: pip install '.[dev]'
      - name: Run pytest
        working-directory: server
        run: pytest

  docker:
    runs-on: ubuntu-latest
    needs:
      - test
      - lint
    steps:
      - uses: actions/checkout@v4
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/fruktus/quadradius-preservation-project
          tags: |
            type=semver,pattern={{version}}
            latest
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
