name: Web App

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  npm:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        working-directory: web
        run: npm i
      - name: Run Linter
        working-directory: web
        run: npm run lint
      - name: Run Server Build
        working-directory: web
        run: npm run build
      - name: Run Export Build
        working-directory: web
        run: npm run export
